language: node_js
before_script:
- yarn install
- mkdir dist
- yarn run build
node_js:
- node
deploy:
  provider: pages
  skip-cleanup: true
  github-token: epXVzE0thzFVpJGAuePkqaA0E2zzkSZyITZHRC6MxfYLs7UF4qf/xpA9IwuNXRHcYWIiJM1ARgq6nsfDOdLBxTn/BJtnjAz3F7wCbJwxUFGhs3pJbDsfHNQN8diwQN3WuanRUo5JCjqd8izV7itsJ+tGWaywX7aY3jikTKNDEPjaREvUjmA67zA61esbPuTqBft40nv7WdsoF8991cSjnNg5sodOhtvq72XiMMTgujRLfSJkln9aNOuCVT490ZaTlyeimovP7zGi/XuEa0Tf6a4ms8NC9U97wKVZS1t+wJi2KStBnVrev4ukmm0t35C5BOShzexpgcXESMEZj8049SjGVNGf/blUNA1NBlph+iQgfzAZLnDNt95aOydm+Yd9nRZ7A+8m294UNIYtG3jLsnYx5hYuBXYfxjNe2Rz+hzYsx3OMtY0LtZ8Z7YH+YxWXB2+KWut/uxLH9FBSlvsIgAv0JbsojvIJjf3LNHIeINgkVkuuWGseS95JvODgh55mV9TJpV7ZCCvyNuhWDqVtXIvr/bKnV7Fxs7dqVOeTDR2QGM/p80JBh3GMYQ1VFq+L6e9OZ0TGcTv95dDGoC8IhAFx1BYhv/zto7JuoKu/TTTB57PMLqawFsCQT8u1CSKpA8OWI6kOb7WWcWP7Izjp7OidFdWMU1FGcrD+KHs2VWc=
  keep-history: true
  local-dir: dist
  on:
    branch: gh-pages
