language: node_js
before_script:
- yarn install
- mkdir dist
- yarn run build
node_js:
- node
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: gh-pages
env:
  global:
    secure: E6eHkhOvdlvVWehFXuPBnNVtuF7rjF+z93gGn1gN2pMsZmiNaU898ilF7iEHxt9zWsk6I3GaB+wFa04WGufCtSDC55SgAgNd7gtM4c5JXEHWZX3yDYOPMKyuF7ouQMx7bzLdr2jxZnlabapV/TmFzUHJBg4ts4MR1T9GRZshBTqNMPw5KOE/GRASSBNFD4+hEXnNXnUf+ynOG28I6f1Pab/ugPahfLYxMzgejpDCxA4IVXT+SjCq4rHZ6GFkjD/DHntry8So6IIripWN/Sh/qEXUp38O2oNNyRlukTcVqgfq4z9IvwLaW104xL4eGW+hlD3HJqjonpda2Y9YNGZeCp+nVQE8Ouuy2Xu78lhpopy5cHFJeuQhdIAStpFmX1bDn2YNbsMHG3007fkTbEAMFfRDtk5AnSM4jFlnNrVwHTUys1AJbV9YhmROHt8ZqedFnk4zUf1SfR8eSm5Wf+DfcF3WHL6AvYBXtjxSamMX5GItwUZrrvU78MQI9zB0JeXWSs+ed6VbbmwnRNxUi8+hKaZm8tMf9kirUR1+veEzO9aAye0yDgydafG+/h3hUgxa3Bp/Eqk3gMqMI09sIzkUE0e0lrmeTs2BJqKxGU5kWUszfCNwtfIHvAEd9mfY9hR7ZxGvcQ6KxTnR+U/RKMiKDfmPE5JSXD0pj84ty4krPWs=
