language: node_js
before_script:
- yarn install
- mkdir dist
- yarn run build
node_js:
- node
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: gh-pages
env:
  global:
    secure: KzS+zgJXJWNx48a/bYFOhEEosAXrGM/3scx6Fm37pf+JUZbqWsF7uy6qw9D0fPCL1gEnsZWiSABdiQzvia3NP5GzFYMPbfzONtTcbu1CdMUikFnYmN4AOJ/cOZdMWimjqguxv1tu/2ZL50C71Ti1rIGrpbHzc+T0hstTJHLsvhlhH5Z3unKGjdcNWPRq+Z8hF+ooWrVM2t6YtUugZnP/zFDUeQN9BA5mYzD2PpOm3YPg119UUT8Z40tiOmooC9EUrxFMw97a7EgjuCNKxZtdUbSD/jLAUyT08Zi/8crt+/iVVFf33zo8OXE9tV/yt8IZSy0hFFoF8+DX/Sj+Aes/rw/tPwXXSxyameLn/gPx3xbZ2saqfgATPegnd1rtixHuXEDxtX4hF87LUbxI6CAoLD0ojAxnjGhkfJmOp3Mn+NlpHjbkiv0yFkOcBV+Lq1CPIJiq9wjr8Ek9nD/ls7FWDPLXlV58Z/LYI3IJ2yLweSP4ulyBCihgPtk0Plp3Jurj0kLHy3R01y1Nu4qTpHcwSruGIK+iMZ5unh4/a5EGCjMrRWzVLs+GXxjJ8FMgcZwpytEdaCYYk9Rolr9w3tmbVM7Si3y6tnBSkXS2G7QIB/v8rF8rKoWs/nfvlrXmpC1rj1wWWF852rwJ8sKeaBq5aADkOOxe6pUbUNTmhbyMBn0=
